name: Docs

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2

      - name: Install dependencies
        run: poetry install

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/_build/html
          cname: django-graphql-jwt.domake.io
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
