name: Docs

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install .[doc]

      - name: Build docs
        run: sphinx-build -b html docs docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/_build
          cname: django-graphql-jwt.domake.io
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
