name: Test Suite

on: [push, pull_request]

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        django-version: ['3.0', '3.1', '3.2', '4.0', '4.1', '4.2']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-django-${{ matrix.django-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Django
        run: pip install django==${{ matrix.django-version }}

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Tests
        run: scripts/test.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v3
